# heart disease prediction

reference: RIPAN, R. C. et al. A Data-Driven Heart Disease Prediction Model Through K-Means Clustering-Based Anomaly Detection. SN Computer Science, [s. l.], v. 2, n. 2, 2021. DOI 10.1007/s42979-021-00518-7. Disponível em: https://search.ebscohost.com/login.aspx?direct=true&db=edssjs&AN=edssjs.4F890368&site=eds-live. Acesso em: 21 out. 2022. https://link.springer.com/article/10.1007/s42979-021-00518-7

In [1]:
# import library/package

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

In [15]:
# import database
hd_df = pd.read_csv("heart.csv")
hd_Df = hd_df.drop(columns="fbs")
hd_Df.head()

age  sex  cp  trestbps  chol  restecg  thalach  exang  oldpeak  slope  ca  \
0   52    1   0       125   212        1      168      0      1.0      2   2   
1   53    1   0       140   203        0      155      1      3.1      0   0   
2   70    1   0       145   174        1      125      1      2.6      0   0   
3   61    1   0       148   203        1      161      0      0.0      2   1   
4   62    0   0       138   294        1      106      0      1.9      1   3   

   thal  target  
0     3       0  
1     3       0  
2     3       0  
3     3       0  
4     2       0

In [31]:
conti = ["trestbps", "chol", "thalach", "oldpeak"]
for i in conti:
    q1 = np.quantile(hd_df[i], .25)
    q3 = np.quantile(hd_df[i], .75)
    iqr = q3 - q1
    max = q3 + 1.5 * iqr
    min = q1 - 1.5 * iqr
    hd_df = hd_df.where(hd_df[i] <= max).where( hd_df[i] >= min).dropna()

In [48]:
Y_df = hd_Df["target"].values.copy()
X_df = hd_Df.iloc[:, 0:12].values.copy()
X_train, X_test, Y_train, Y_test = train_test_split(X_df, Y_df, test_size=0.2, random_state=1)
Y_train = Y_train.reshape(Y_train.shape[0], 1)
Y_test = Y_test.reshape(Y_test.shape[0], 1)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(820, 12)
(205, 12)
(820, 1)
(205, 1)


#### knn

In [55]:
knnmodel_1 = KNeighborsClassifier(n_neighbors=3)
knnmodel_1.fit(X_train, Y_train)

/Users/apple/Library/Python/3.8/lib/python/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [56]:
train_predict = knnmodel_1.predict(X_train)
np.unique(train_predict)

array([0, 1])

In [57]:
train_confusion = metrics.confusion_matrix(Y_train, train_predict)
train_confusion

array([[388,   2],
       [  5, 425]])

In [58]:
tn_tr, fp_tr, fn_tr, tp_tr = train_confusion.ravel()
train_error_rate = (fn_tr + fp_tr)/(tn_tr+fp_tr + fn_tr + tp_tr)
train_error_rate

0.00853658536585366

In [59]:
test_predict = knnmodel_1.predict(X_test)
test_confusion = metrics.confusion_matrix(Y_test, test_predict)
test_confusion

array([[105,   4],
       [ 10,  86]])

In [60]:
tn_te, fp_te, fn_te, tp_te = test_confusion.ravel()
test_error_rate = (fn_te + fp_te)/(tn_te+fp_te + fn_te + tp_te)
test_error_rate

0.06829268292682927

In [12]:
list = np.array([1, 3, 5, 6]).reshape(1, -1)
pd.DataFrame(list)

0  1  2  3
0  1  3  5  6